### ISSUE TITLE
Error During Setup

### ISSUE THREAD

**Issue by droach1985** [CSPF-Founder/cm#1]
Whenever I try to run the setup the database is created but it does not create the SuperAdmin account.  I have tried changing the username to just 'admin' but I get the same issue.  I also think its weird to have two inputs for the super admin username.  If both inputs are being passed I would assume that would be the cause of the issue but I have not php'd in a while so I am not sure.  I will look at this if I can get some time but I figured I should throw it up here and see if there is already a fix.  See the error below. 

500
Debug Mode is On! If you are running in production, turn it off
Fatal Error

Uncaught Exception - "ErrorException"

Message htmlentities() expects parameter 1 to be string, array given

Stack Trace :

#0 [internal function]: Core\Error::errorHandler(2, 'htmlentities() ...', '/opt/cm/web/Cor...', 27, Array)
#1 /opt/cm/web/Core/Security/Validator.php(27): htmlentities(Array, 3, 'UTF-8')
#2 /opt/cm/web/Core/View.php(114): Core\Security\Validator::sanitizeXss(Array)
#3 /opt/cm/web/App/Views/Setup/index.php(30): Core\View::securePrint(Array)
#4 /opt/cm/web/Core/View.php(27): require('/opt/cm/web/App...')
#5 /opt/cm/web/App/Controllers/SetupController.php(93): Core\View::render('Setup/index.php', Array)
#6 /opt/cm/web/App/Controllers/SetupController.php(75): App\Controllers\SetupController->displayErrorFormNonFilteredAction(Array)
#7 [internal function]: App\Controllers\SetupController->indexNonFilteredAction()
#8 /opt/cm/web/Core/Controller.php(70): call_user_func_array(Array, Array)
#9 /opt/cm/web/Core/Router.php(142): Core\Controller->filterAction('index', Array)
#10 /opt/cm/web/public/index.php(63): Core\Router->dispatch('setup/index')
#11 {main}                        
Throws in : /opt/cm/web/Core/Security/Validator.php on line 27

}
If the problem persists feel free to contact us

**Comment by CSPF-Founder** [comment]
The two inputs are not the username fields.  The first one is name and second one is username.

**Comment by CSPF-Founder** [comment]
There was an exception in handling the error message.  updated the code.  Please delete the database and re-create the database.  Before going to setup page, make sure you have created database called "cm".

**Comment by droach1985** [comment]
Thank you for clearing this up.  The fields are less ambiguous with the value field update.  The setup is completing without issue.
